### ISSUE TITLE
Builds do not start on OKD / OpenShift

### ISSUE THREAD

**Issue by VGerris** [okd-project/okd-coreos-pipeline#40]
After following the instructions, the builds do not work on the latest OKD 4.11 from the current CRC. 
The OpenShift instructions for Tekton show the setup of a service account with anyuid:
https://tekton.dev/docs/pipelines/install/ (OpenShift tab, which mentions a non-existing system account ?).

Unfortunately that does not seem to work.
I can imagine that because of the kvm plugin it uses something may go wrong on CRC ( OpenShift Local ) ?
I would just think that when building OKD images, OKD on CRC would be a logical choice, so whatever is needed should be documented, or mentioned that it does not work following the instructions.

**Comment by VGerris** [comment]
A workaround for installation is : 
- after tekton installation, switch to the project logged in as kubeadmin : oc project tekton-operator
- Then run the commands to allow the proper rights as described in the install docs
oc adm policy add-scc-to-user anyuid -z tekton-pipelines-controller
oc adm policy add-scc-to-user anyuid -z tekton-pipelines-webhook
- then : oc apply -k overlays/local should complete without problems

After that, I never get a pod with:
$ kubectl get all -n okd-coreos-pipeline
NAME                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/device-plugin-kvm   0         0         0       0            0           <none>          5m5s

Then I noticed in the events there was another rights issue, which I could fix by applying the above and then : 
$ oc get ds device-plugin-kvm --output yaml --namespace okd-coreos-pipeline | oc adm policy scc-subject-review --filename -
RESOURCE                      ALLOWED BY             
DaemonSet/device-plugin-kvm   hostpath-provisioner   
$ oc adm policy add-scc-to-user hostpath-provisioner -z default -n okd-coreos-pipeline

Then the pod starts.
I haven't setup a registry and s3 storage so I am not sure if this should give me a working build.
I think some additional info on how to troubleshoot this would be useful.

**Comment by LorbusChris** [comment]
A lot has change in this repo and we're not explicitly supporting CRC. I'll close but please feel free to re-open if the issue still persists.
